# Configure main menu and social menu
[[main]]
identifier = "home"
name = "首页"
weight = -100
url = "https://gaein.cn"
[main.params]
icon = "home"
newtab = false

[[main]]
identifier = "links"
name = "链接"
weight = 100
url = "https://www.gaein.cn/friends"
[main.params]
icon = "link"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nidbCN"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"
